-- =========================================================================
-- Portão estatístico automático
--
-- Aplicada no projeto xzqmfcxtvfffgrmqqzdz em 2026-08-16.
-- Este arquivo existe para que o histórico do repositório bata com o
-- estado real do banco.
--
-- PROBLEMA
-- Os critérios de morte estavam gravados como TEXTO em
-- hipoteses_pesquisa.criterio_morte. Nada os verificava. A aplicação
-- dependia de alguém lembrar de rodar a conta — em fevereiro de 2027,
-- depois de seis meses de investimento no experimento.
--
-- É exatamente aí que disciplina estatística falha: não na hora de
-- escrever a regra, na hora de aplicá-la contra o próprio desejo.
--
-- O QUE ISTO FAZ
-- Avalia sozinho, todo dia às 06:20 UTC, cada configuração em coleta, e
-- diz em que situação ela está. NÃO encerra nada automaticamente:
-- encerrar é decisão humana e deve ficar registrada como tal. O que ele
-- impede é a decisão ser adiada por não se saber que o critério já foi
-- atingido.
--
-- O registro diário também responde a pergunta que mais importa depois:
-- QUANDO o critério foi atingido pela primeira vez. Se a morte foi
-- decidida três semanas depois de o gatilho disparar, isso fica visível
-- em `portao_estatistico_avaliacoes`.
--
-- CONSULTA DE USO
--   select * from vw_portao_estatistico;
--
-- Nenhuma política de execução é alterada.
-- =========================================================================

create table if not exists public.portao_estatistico_avaliacoes (
  id bigint generated by default as identity primary key,
  avaliado_em timestamptz not null default now(),
  config_id uuid not null references public.forward_test_config(id),
  config_versao text not null,
  hipotese_id uuid references public.hipoteses_pesquisa(id),
  operacoes_fechadas integer not null,
  soma_r numeric,
  media_r numeric,
  desvio_r numeric,
  t_observado numeric,
  t_exigido numeric,
  amostra_alvo integer,
  gatilho_futilidade_n integer,
  situacao text not null,
  detalhe text,
  unique (config_id, avaliado_em)
);

create index if not exists portao_estatistico_config_idx
  on public.portao_estatistico_avaliacoes (config_id, avaliado_em desc);

alter table public.portao_estatistico_avaliacoes enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='portao_estatistico_avaliacoes'
      and policyname='portao estatistico visivel para autenticados'
  ) then
    create policy "portao estatistico visivel para autenticados"
      on public.portao_estatistico_avaliacoes
      for select to authenticated using (true);
  end if;
end $$;

create or replace view public.vw_portao_estatistico
with (security_invoker=true) as
with base as (
  select
    c.id as config_id,
    c.versao as config_versao,
    c.amostra_alvo,
    c.criado_em,
    h.id as hipotese_id,
    h.t_minimo_exigido as t_exigido,
    -- Gatilho de futilidade na metade do alvo. Só pode matar, nunca
    -- aprovar, e por isso não infla o erro tipo I.
    greatest(30, c.amostra_alvo / 2) as gatilho_futilidade_n,
    count(s.resultado_r) as operacoes_fechadas,
    sum(s.resultado_r)::numeric as soma_r,
    avg(s.resultado_r)::numeric as media_r,
    stddev_samp(s.resultado_r)::numeric as desvio_r
  from public.forward_test_config c
  left join public.hipoteses_pesquisa h
    on h.estrategias = c.estrategias
   and h.status in ('registrada','coletando')
  left join public.forward_test_signals s
    on s.config_id = c.id
   and s.resultado_r is not null
  where c.coletar = true
  group by c.id, c.versao, c.amostra_alvo, c.criado_em,
           h.id, h.t_minimo_exigido
),
calc as (
  select *,
    case
      when operacoes_fechadas >= 2 and coalesce(desvio_r,0) > 0
      then (media_r / desvio_r) * sqrt(operacoes_fechadas)::numeric
    end as t_observado,
    -- Ritmo observado, para projetar quando o alvo chega.
    case
      when extract(epoch from (now() - criado_em)) > 0
      then operacoes_fechadas
           / (extract(epoch from (now() - criado_em)) / 86400.0)::numeric
    end as fechados_por_dia
  from base
)
select
  config_id, config_versao, hipotese_id,
  operacoes_fechadas, amostra_alvo, gatilho_futilidade_n,
  round(soma_r, 2) as soma_r,
  round(media_r, 4) as media_r,
  round(desvio_r, 4) as desvio_r,
  round(t_observado, 3) as t_observado,
  t_exigido,
  round(fechados_por_dia, 2) as fechados_por_dia,
  case
    when fechados_por_dia > 0 and operacoes_fechadas < amostra_alvo
    then ceil((amostra_alvo - operacoes_fechadas) / fechados_por_dia)
  end as dias_estimados_ate_alvo,
  case
    when operacoes_fechadas >= amostra_alvo
         and coalesce(t_observado, -99) >= coalesce(t_exigido, 3.469)
      then 'APROVADO PARA DISCUSSAO'
    when operacoes_fechadas >= amostra_alvo
      then 'MORTE POR INSUFICIENCIA'
    when operacoes_fechadas >= gatilho_futilidade_n
         and coalesce(soma_r, 0) <= 0
      then 'MORTE POR FUTILIDADE'
    else 'COLETANDO'
  end as situacao,
  case
    when operacoes_fechadas >= amostra_alvo
         and coalesce(t_observado, -99) >= coalesce(t_exigido, 3.469)
      then 'Alvo atingido com t suficiente. Libera DISCUSSAO de Testnet, '
           || 'nunca conta real. Reveja a carga_de_busca antes: se ela subiu, '
           || 'o t exigido subiu junto.'
    when operacoes_fechadas >= amostra_alvo
      then 'Alvo de amostra atingido e o t observado ficou abaixo do exigido. '
           || 'Encerre a hipotese sem ajustar parametros. Ajustar agora '
           || 'transforma o experimento em busca.'
    when operacoes_fechadas >= gatilho_futilidade_n
         and coalesce(soma_r, 0) <= 0
      then 'Metade do alvo com soma de R nao positiva. O criterio de '
           || 'futilidade pre-registrado foi atingido. Encerre e economize '
           || 'a espera.'
    else 'Coleta em andamento. Nao consulte o resultado parcial para decidir '
         || 'se continua: isso e o que o pre-registro existe para impedir.'
  end as detalhe
from calc;

create or replace function public.registrar_portao_estatistico()
returns integer
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare inseridas integer;
begin
  insert into public.portao_estatistico_avaliacoes (
    config_id, config_versao, hipotese_id,
    operacoes_fechadas, soma_r, media_r, desvio_r,
    t_observado, t_exigido, amostra_alvo, gatilho_futilidade_n,
    situacao, detalhe
  )
  select
    config_id, config_versao, hipotese_id,
    operacoes_fechadas, soma_r, media_r, desvio_r,
    t_observado, t_exigido, amostra_alvo, gatilho_futilidade_n,
    situacao, detalhe
  from public.vw_portao_estatistico;

  get diagnostics inseridas = row_count;
  return inseridas;
end $$;

revoke all on function public.registrar_portao_estatistico() from public;
grant execute on function public.registrar_portao_estatistico() to service_role;

grant select on public.vw_portao_estatistico,
  public.portao_estatistico_avaliacoes to authenticated, service_role;

do $$
declare job_record record;
begin
  for job_record in
    select jobid from cron.job where jobname='vigia-portao-estatistico-diario'
  loop
    perform cron.unschedule(job_record.jobid);
  end loop;
end $$;

select cron.schedule(
  'vigia-portao-estatistico-diario',
  '20 6 * * *',
  $cron$ select public.registrar_portao_estatistico(); $cron$
);

select public.registrar_portao_estatistico();
